on: push
name: Build and Deploy on Push
jobs:
  installDependencies:
    name: Install dependencies
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Install dependencies
      uses: nuxt/actions-yarn@master
      with:
        entrypoint: yarn
        args: install
    - name: Build site
      uses: nuxt/actions-yarn@master
      with:
        entrypoint: yarn
        args: build
    - name: Deploy
      uses: amondnet/now-deployment@v1
      with:
        zeit-token: ${{ secrets.ZEIT_TOKEN }}
    - name: On Master
      uses: actions/bin/filter@master
      with:
        args: branch master
    - name: Alias
      uses: amondnet/now-deployment@v1
      with:
        zeit-token: ${{ secrets.ZEIT_TOKEN }}
        now-args: alias
